# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureAppServiceManage@0
  inputs:
    azureSubscription: 'Azure for Students(36000fc5-3a82-4990-9709-6a571fb9219e)'
    Action: 'Stop Azure App Service'
    WebAppName: 'MI1-Autodeploy-R4'
  displayName: 'Stopping Web Service'
- task: NodeTool@0

  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install and start'

- task: AzureAppServiceManage@0
  inputs:
    azureSubscription: 'Azure for Students(36000fc5-3a82-4990-9709-6a571fb9219e)'
    Action: 'Start Azure App Service'
    WebAppName: 'MI1-Autodeploy-R4'
  displayName: 'Starting Web Service'